export default [
    {title:"Advanced WMS",id:1},
    {title:"Master Planning",id:2},
    {title:"AS-IS/TO-BE Workflows",id:3},
    {title:"Mobile Device Config",id:4},
    {title:"Inventory & Procurement",id:5},
    {title:"Lean Six Sigma",id:6},
    {title:"Wave/Replenishment",id:7},
    {title:"Field Service",id:8},
    {title:"SDD/FDD",id:9},
    {title:"Production Control",id:10},
    {title:"Process Mapping",id:11},
    {title:"SQL",id:12},
    {title:"BOMs & Routes",id:13},
    {title:"Business Process Re-engineering",id:14},
    {title:"JavaScript",id:15},
]